const CartActionTypes = {
  ADD_ITEM: "ADD_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
  CLEAR_ITEM: "CLEAR_ITEM",
  CLEAR_ITEMS: "CLEAR_ITEMS",
  SHOW_CART: "SHOW_CART",
  HIDE_CART: "HIDE_CART",
  SHOW_ADD_ITEM_MESSAGE: "SHOW_ADD_ITEM_MESSAGE",
  HIDE_ADD_ITEM_MESSAGE: "HIDE_ADD_ITEM_MESSAGE",
  SHOW_TRIANGLE: "SHOW_TRIANGLE",
  HIDE_TRIANGLE: "HIDE_TRIANGLE",
};

export default CartActionTypes;
