const CheckoutActionTypes = {
  UPDATE_CHECKOUT_FORM_FIELD: "UPDATE_CHECKOUT_FORM_FIELD",
  CLEAR_CHECKOUT_FORM: "CLEAR_CHECKOUT_FORM",
  SET_ORDER_START: "SET_ORDER_START",
  SET_ORDER_SUCCESS: "SET_ORDER_SUCCESS",
  SET_ORDER_FAILURE: "SET_ORDER_FAILURE",
  SHOW_CHECKOUT_MODAL: "SHOW_CHECKOUT_MODAL",
  HIDE_CHECKOUT_MODAL: "HIDE_CHECKOUT_MODAL",
};

export default CheckoutActionTypes;
