const ProductActionTypes = {
  FETCH_PRODUCT_START: "FETCH_PRODUCT_START",
  FETCH_PRODUCT_SUCCESS: "FETCH_PRODUCT_SUCCESS",
  FETCH_PRODUCT_FAILURE: "FETCH_PRODUCT_FAILURE",
  SELECT_OPTION: "SELECT_OPTION",
  SELECT_PRODUCT_ICON: "SELECT_PRODUCT_ICON",
  SELECT_BACKGROUND_IMAGE: "SELECT_BACKGROUND_IMAGE",
  SHOW_DELIVERY_DETAILS: "SHOW_DELIVERY_DETAILS",
  SHOW_SUBSTITUTION_POLICY: "SHOW_SUBSTITUTION_POLICY",
  HIDE_DELIVERY_DETAILS: "HIDE_DELIVERY_DETAILS",
  HIDE_SUBSTITUTION_POLICY: "HIDE_SUBSTITUTION_POLICY",
};

export default ProductActionTypes;
