const SearchPanelHeaderActionTypes = {
  CHANGE_QUERY_VALUE: "CHANGE_QUERY_VALUE",
  FETCH_ITEMS_BY_QUERY_START: "FETCH_ITEMS_BY_QUERY_START",
  FETCH_ITEMS_BY_QUERY_SUCCESS: "FETCH_ITEMS_BY_QUERY_SUCCESS",
  FETCH_ITESM_BY_QUERY_FAILURE: "FETCH_ITEMS_BY_QUERY_FAILURE",
  CLEAR_QUERY_VALUE: "CLEAR_QUERY_VALUE",
};

export default SearchPanelHeaderActionTypes;
